### ISSUE TITLE
no /dev/uio file created when inserting axis module

### ISSUE THREAD

**Issue by luntik2012** [bmartini/zynq-axis#1]

**Comment by luntik2012** [comment]
no /dev/axis also

**Comment by luntik2012** [comment]
wrong dtb file...

**Comment by bmartini** [comment]
If you have a dtb file that works on a new kernel version and is different from the one that's in the repo I would be happy to add it if you give me a copy.

**Comment by luntik2012** [comment]
No, it's OK. I had wrong dtb file in my rootfs. Now there are /dev/axis -> /dev/uio0.
Is it necessary to build custom IP to get this driver working?

**Comment by bmartini** [comment]
Not sure what you are asking about "custom IP". To get this driver working you need a Vivado project that implements the Xilinx DMA IP. You will also need a devicetree to correctly ID the DMA IP and then the driver/udev.rules/library etc. There was an example here: https://github.com/bmartini/zedboard-vivado-loopback but I've not updated it for a while so don't know if it still works, at the very least its a starting point.

**Comment by raffaelesury** [comment]
isn't the AXIS hardware module custom IP? Can the driver be used with xilinx DMA IP?
